import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFC12F);
const KSecondaryColor = Color(0xFFFFE6AC);
const kProductCollection = 'Products';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kOnActiveColor = Color(0xFFC1BDb8);
const kJackets = 'jackets';
const kTrousers = 'trouser';
const kTshirts = 'tshirts';
const kShoes = 'shoes';
const kOrders = 'Orders';
const kOrdersDetails = 'OrdersDetails';
const kTotalPrice = 'TotalPrice';
const kAddress = 'Address';
const kProductQuanity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
